config/routes.rb
Rails.application.routes.draw do
  resources :trainings
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  root 'static_pages#home'
  
  get '/help', to: 'static_pages#help'
  get '/about', to: 'static_pages#about'
  get '/contact', to: 'static_pages#contact'

  get '/signup',  to: 'users#new'
  post '/signup', to: 'users#create'

  get '/login', to: 'sessions#new'
  post '/login', to: 'sessions#create'
  delete '/logout', to: 'sessions#destroy'

  resources :users
end

app/models/training.rb
class Training < ApplicationRecord
  has_many :user_trainings
  has_many :users, through: :user_trainings
end

app/controllers/trainings_controller.rb
class TrainingsController < ApplicationController
  before_action :set_training, only: [:show, :edit, :update, :destroy]

  # GET /trainings
  # GET /trainings.json
  def index
    @trainings = Training.paginate(page: params[:page], per_page: 10).order(date: :asc)
  end

  # GET /trainings/1
  # GET /trainings/1.json
  def show
  end

  # GET /trainings/new
  def new
    @training = Training.new
    @students = User.students
    @teachers = User.teachers
  end

  # GET /trainings/1/edit
  def edit
  end

  # POST /trainings
  # POST /trainings.json
  def create
    @training = Training.new(training_params)

    respond_to do |format|
      if @training.save
        format.html { redirect_to @training, notice: 'Training was successfully created.' }
        format.json { render :show, status: :created, location: @training }
      else
        format.html { render :new }
        format.json { render json: @training.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /trainings/1
  # PATCH/PUT /trainings/1.json
  def update
    respond_to do |format|
      if @training.update(training_params)
        format.html { redirect_to @training, notice: 'Training was successfully updated.' }
        format.json { render :show, status: :ok, location: @training }
      else
        format.html { render :edit }
        format.json { render json: @training.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /trainings/1
  # DELETE /trainings/1.json
  def destroy
    @training.destroy
    respond_to do |format|
      format.html { redirect_to trainings_url, notice: 'Training was successfully deleted.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_training
      @training = Training.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def training_params
      params.require(:training).permit(:date, :location, :description)
    end
end

app/helpers/trainings_helper.rb
module TrainingsHelper
end

app/views/trainings/_form.html.haml
-# frozen_string_literal: true
= simple_form_for(@training) do |f|
  = f.error_notification
  = f.error_notification message: f.object.errors[:base].to_sentence if f.object.errors[:base].present?

  .form-inputs
    #date_picker
      = f.input :date
    = f.input :location
    = f.input :description

  .form-actions
    = f.submit 'Crear', class: 'btn btn-primary'

app/views/trainings/_training.html.haml
%tr
  %td= training.description
  %td= training.date
  %td= 'maestro'
  %td= training.location
  - if current_user.admin?
    %td= link_to '', training, class: 'btn btn-default btn-xs glyphicon glyphicon-search'
    %td= link_to '', edit_training_path(training), class: 'btn btn-warning btn-xs glyphicon glyphicon-pencil'
    %td= link_to '', training, method: :delete, data: { confirm: 'Are you sure?' }, class: 'btn btn-danger btn-xs glyphicon glyphicon-trash'
    

app/views/trainings/_trainings_list.html.haml
%table.table.table-hover
  %thead
    %tr
      %th Descripción
      %th Fecha
      %th Maestro
      %th Gimnasio
      %th{colspan: '3'}
  %tbody
    .trainings
      = render @trainings
= will_paginate

app/views/trainings/edit.html.haml
%h1 Editing training

= render 'form'

= link_to 'Show', @training
\|
= link_to 'Back', trainings_path

app/views/trainings/index.html.haml
- provide(:title, 'Entrenamientos')
%h1 Entrenamientos

#trainings_list
  = render 'trainings_list'
  
- if @current_user&.admin?
  %br/
  = link_to 'Create training', new_training_path, class: 'btn btn-primary'

app/views/trainings/new.html.haml
%h1 Nuevo entrenamiento
.row
  .col-md-6.col-md-offset-3
    = render 'form'

= link_to 'Atrás', trainings_path, class: 'btn'

app/views/trainings/show.html.haml
%p#notice= notice

%p
  %b Descripción:
  = @training.description
%p
  %b Fecha:
  = @training.date
%p
  %b Gimnasio:
  = @training.location

= link_to 'Edit', edit_training_path(@training)
\|
= link_to 'Back', trainings_path