config/routes.rb
Rails.application.routes.draw do
  resources :trainings
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  root 'static_pages#home'
  
  get '/help', to: 'static_pages#help'
  get '/about', to: 'static_pages#about'
  get '/contact', to: 'static_pages#contact'

  get '/signup',  to: 'users#new'
  post '/signup', to: 'users#create'

  get '/login', to: 'sessions#new'
  post '/login', to: 'sessions#create'
  delete '/logout', to: 'sessions#destroy'

  resources :users
end

app/views/layouts/_footer.html.haml
%footer.footer
  %small
    = link_to image_tag('bbj_logo.png', alt: 'BJJ logo'), 'http://barcelonajiujitsu.com/', target: '_blank', id: 'logo'
  %nav
    %ul
      %li= image_tag('https://lipis.github.io/flag-icon-css/flags/4x3/br.svg', alt: 'Brazil flag', size: 30, class: 'flag')
      %li= image_tag('https://lipis.github.io/flag-icon-css/flags/4x3/es.svg', alt: 'Spain flag', size: 30, class: 'flag')
      %li= link_to 'About', about_path
      %li= link_to 'Contact', contact_path

app/views/layouts/_header.html.haml
%header.navbar.navbar-fixed-top.navbar-inverse
  .container
    //= link_to image_tag('bbj_logo.png', alt: 'BJJ logo'), 'http://barcelonajiujitsu.com/', target: '_blank', id: 'logo'
    = link_to 'BCN Jiu Jitsu', root_path, id: 'logo'
    %nav
      %ul.nav.navbar-nav.navbar-right
        %li= link_to 'Home', root_path
        %li= link_to 'Ayuda', help_path
        - if logged_in?
          %li= link_to 'Usuarios', users_path
          %li= link_to 'Entrenamientos', trainings_path
          //= gravatar_for @current_user
          %li.dropdown
            %a.dropdown-toggle{'data-toggle' => 'dropdown', href: '#'}
              = gravatar_for(current_user, size: 40, type: 'gravatar_header')
              %b.caret
            %ul.dropdown-menu
              %li= current_user.name
              %li.divider
              %li= link_to 'Perfil', current_user
              %li= link_to 'Ajustes', edit_user_path(current_user)
              %li.divider
              %li= link_to 'Sign out', logout_path, method: :delete
        - else
          %li= link_to 'Sign in', login_path

app/views/layouts/_rails_default.html.haml
= csrf_meta_tags
= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload'                   |
= javascript_include_tag 'application', 'data-turbolinks-track': 'reload'

app/views/layouts/_shim.html.haml
/[if lt IE 9]
  <script src="//cdnjs.cloudflare.com/ajax/libs/html5shiv/r29/html5.min.js">
  </script>

app/views/layouts/application.html.haml
!!!
%html
  %head
    %title= full_title(yield(:title))
    = render 'layouts/rails_default'
    = render 'layouts/shim'
    = favicon_link_tag ('bbj_logo.png')
  %body
    = render 'layouts/header'
    .container
      - flash.each do |message_type, message|
        = content_tag(:div, message, class: "alert alert-#{message_type}")
      = yield
      = render 'layouts/footer'
      = debug(params) if Rails.env.development?